#baseURL  = "https://blog.jhonatamenezes.com.br/"
theme = "cocoa"
languageCode = "pt-br"
buildDrafts = false
publishdir = "public"
author = "Jhonata Menezes dos Santos"
title = "Blog do Jhow"
canonifyURLs = true
googleAnalytics = "UA-87718763-5"
disqusshortname = "blog-do-jhow"


[params]
dateform = "2 Jan, 2006"
dateformfull = "2 Mon Jan 2006 15:04:05 MST"
description = "Passando o conhecimento para a internet"
logofile = ""
faviconfile = ""
highlightjs = true
progressively = true
lang = "pt-br"
github = "https://github.com/jhonata-menezes/"
email = "jhonatamenezes10@gmail.com"
linkedin = "https://www.linkedin.com/in/jhonata-santos-a3659011a/"
twitter = ""
author = "Jhonata Menezes dos Santos"
avatar = "img/avatar.jpeg"
